### ISSUE TITLE
Could you add some documentation please?

### ISSUE THREAD

**Issue by CHJ85** [AudDMusic/youtube-recognizer#1]
Hi there. Could you add some documentation, please?
I installed GoLang and tried to run "go run main.go"
Gave me this error:
```
main.go:39:2: cannot find package "github.com/AudDMusic/audd-go" in any of:
        /usr/lib/go-1.13/src/github.com/AudDMusic/audd-go (from $GOROOT)
        /home/chris/go/src/github.com/AudDMusic/audd-go (from $GOPATH)
main.go:40:2: cannot find package "github.com/rylio/ytdl" in any of:
        /usr/lib/go-1.13/src/github.com/rylio/ytdl (from $GOROOT)
        /home/chris/go/src/github.com/rylio/ytdl (from $GOPATH)
```
Where do I find this missing package?
Honestly I am not familiar with GO.
Please help. Thanks.

**Comment by Mihonarium** [comment]
Hey,
In order to install those packages, you need to do 
`go get github.com/AudDMusic/audd-go`
and
`go get github.com/rylio/ytdl`
in the console

**Comment by CHJ85** [comment]
Ah. Thank you!

**Comment by GamesHarder** [comment]
Does this still work?
The installation and everything?

**Comment by Mihonarium** [comment]
@GamesHarder I've updated the code. Installation via 
```
go get ./...
go build
```
should work

**Comment by Mihonarium** [comment]
@GamesHarder see also the [windows](https://github.com/AudDMusic/youtube-recognizer/releases/download/0.0.2/youtube-recognizer.exe) and [linux](https://github.com/AudDMusic/youtube-recognizer/releases/download/0.0.2/youtube-recognizer) binaries

**Comment by GamesHarder** [comment]
It works now, thank you.
Also, do you know how to resolve Error code 501? "couldn't extract the audio"
